In [33]:
import numpy as np
import scipy as sc
from IPython.display import display, Math
from pylab import *
import matplotlib.pyplot as plt
import seaborn as sns
import math

## listing 1

In [34]:
x = 10
y = (x - 3)**2 + 1

tmp = 10 ** 50
x = tmp ** (1 / math.log10(tmp))
"x & y: ", x, y

('x & y: ', 10.0, 50)

## listing 2

In [35]:
print(1 + 3 - 7 == -3)
print(-(-2) == 2)

True
True


## listing 3

In [41]:
print(5/2 == 2.5)
print(5/2 == 2.5)
print((2*4+3)/4 == 2.75)

True
True
True


## listing 4

In [62]:
print(1*2*3*4*5 == 120)
print(math.factorial(5) == 120)

print(np.sqrt(4) == 2)
# Round value due to 123**(1/3) is equal to 4.(9)
print(round(125**(1/3), 2) == 5)
print(abs(-10) == 10)
print(np.power(np.exp(1), np.log(3)) == 3)
print(3**2 == 9)
print(round(10**(0.2), 3) == 1.585)
print((1+2)*3 == 9)
print(1 + 2*3 == 7)

True
True
True
True
True
True
True
True
True
True


## listing 5

In [70]:
np.sum([i for i in range(1, 11)]) == 55

True

In [90]:
product = np.prod([i for i in range(1, 11)])
print(product)
print(f" product == 3.629 * 10^6: {product == 3.629 * 10**6}")

3628800
 product == 3.629 * 10^6: False


# listing 6 

In [104]:
x = 2j
print(x*x == -4)
print(x**2 == -4)

y = np.add(19.785j, 0.1)

print(f"im(y) = {np.imag(y)}")
print(f"Re(y) = {np.real(y)}")

z = 23 * np.exp(1)**(0.1j)
print(round(abs(z), 2) == 23)
print(f"arg(z) = {np.angle(z)}")

True
True
im(y) = 19.785
Re(y) = 0.1
True
arg(z) = 0.1


listing 7

In [111]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.array([1, 4, 7, 2, 5, 8, 3, 6, 8]).reshape(3, 3)
print(f"> a:  \n {a} \n> b: {b}")
print(f"> 2*a:\n {2*a}")
print(f"> b*a:\n {b*a}")
print(f"> b^T:\n {b.T}")

> a:  
 [[1]
 [2]
 [3]] 
> b: [[1 4 7]
 [2 5 8]
 [3 6 8]]
> 2*a:
 [[2]
 [4]
 [6]]
> b*a:
 [[ 1  4  7]
 [ 4 10 16]
 [ 9 18 24]]
> b^T:
 [[1 2 3]
 [4 5 6]
 [7 8 8]]


In [129]:
C = np.array([1, 0, 0, 1, 0, 0]).reshape(3, 2)
print(f"> C: \n{C}")
print(f">B*C: \n{np.dot(b * C)}")
D = np.array([1, 4, 2, 2, 5, 2, 3, 0, 1])
print(f"> |D|: \n{np.sum(D)}")
print(f">B*C: \n{b*C}")

> C: 
[[1 0]
 [0 1]
 [0 0]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 