# Варіант 10

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
from IPython.display import display, HTML

warnings.filterwarnings("ignore")


In [10]:
import numpy as np

def square_root_method(A, b, precision=6):
    n = len(A)
    T = np.zeros((n, n))
    
    print("Початкова матриця A:")
    print(np.round(A, precision))
    print("\nПочатковий вектор b:")
    print(np.round(b, precision))
    
    for i in range(n):
        for j in range(i, n):
            if i == j:
                sum_k = sum(T[k, i]**2 for k in range(i))
                T[i, i] = np.sqrt(A[i, i] - sum_k)
            else:
                sum_k = sum(T[k, i] * T[k, j] for k in range(i))
                T[i, j] = (A[i, j] - sum_k) / T[i, i]
            
            T[i, j] = round(T[i, j], precision)
    
    print("\nМатриця T після факторизації:")
    print(np.round(T, precision))
    

    y = np.zeros(n)
    for i in range(n):
        sum_k = sum(T[k, i] * y[k] for k in range(i))
        y[i] = (b[i] - sum_k) / T[i, i]
        y[i] = round(y[i], precision)
    
    print("\nПроміжний вектор y:")
    print(np.round(y, precision))
    
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        sum_k = sum(T[i, k] * x[k] for k in range(i+1, n))
        x[i] = (y[i] - sum_k) / T[i, i]
        x[i] = round(x[i], precision)
    
    return x

# Використання методу
A = np.array([
    [1.0, 0.42, 0.54, 0.66],
    [0.42, 1.0, 0.32, 0.44],
    [0.54, 0.32, 1.0, 0.22],
    [0.66, 0.44, 0.22, 1.0]
])

b = np.array([0.3, 0.5, 0.7, 0.9])

x = square_root_method(A, b)

print("\nРозв'язок x:")
print(np.round(x, 6))

# Перевірка
r = b - np.dot(A, x)
print("\nВектор нев'язки r = b - Ax:")
print(np.round(r, 6))

Початкова матриця A:
[[1.   0.42 0.54 0.66]
 [0.42 1.   0.32 0.44]
 [0.54 0.32 1.   0.22]
 [0.66 0.44 0.22 1.  ]]

Початковий вектор b:
[0.3 0.5 0.7 0.9]

Матриця T після факторизації:
[[ 1.        0.42      0.54      0.66    ]
 [ 0.        0.907524  0.102697  0.179389]
 [ 0.        0.        0.835376 -0.185333]
 [ 0.        0.        0.        0.7056  ]]

Проміжний вектор y:
[0.3 0.  0.  0. ]

Проміжний вектор y:
[0.3     0.41211 0.      0.     ]

Проміжний вектор y:
[0.3      0.41211  0.593359 0.      ]

Проміжний вектор y:
[0.3      0.41211  0.593359 1.045976]

Розв'язок x:
[-1.257793  0.043487  1.039167  1.482392]

Вектор нев'язки r = b - Ax:
[-0.e+00  0.e+00 -1.e-06  0.e+00]
