In [1]:
import numpy as np
np.set_printoptions(precision=5, suppress=False)

In [2]:
## Utils
def multiply_arrays(matrixF, matrixS):
    """
    Function to multiply two matrices.
    Assumes matrixF is m x n and matrixS is n x p.
    Returns a matrix of size m x p.
    """
    m = len(matrixF)
    n = len(matrixF[0])
    p = len(matrixS[0])
    if n != len(matrixS):
        return None
    matrixR = [[0 for _ in range(p)] for _ in range(m)]
    for i in range(m):
        for j in range(p):
            for k in range(n):
                matrixR[i][j] += matrixF[i][k] * matrixS[k][j]
    return matrixR

def multiply3Arrays(matrixF, matrixS, matrixT):
    if len(matrixF[0]) != len(matrixS):
        return None
    
    matrixR = multiply_arrays(matrixF, matrixS)
    matrixR = multiply_arrays(matrixR, matrixT)
    return matrixR

def matrixA_to_normal_frobenius_form(matrixA:np.ndarray):
    P = matrixA.copy()
    n = len(matrixA)
    matrixM = [[0] * n for _ in range(n)]
    matrixMInverse = [[0] * n for _ in range(n)]
    for i in range(n):
        matrixM[i][i] = 1
        matrixMInverse[i][i] = 1
    
    m = n - 1
    
    for k in range(m):
        for i in range(1, m + 1):
            for j in range(m + 1):
                if m - k == m - i + 1:
                    if j != m - i:
                        matrixM[m - i][j] = -1 * P[m - i + 1][j] / P[m - i + 1][m - k - 1]
                    else:
                        matrixM[m - i][j] = 1 / P[m - i + 1][m - k - 1]
                    matrixMInverse[m - i][j] = P[m - i + 1][j]

        for i in range(n):
            for j in range(n):
                if i == m - k:
                    if i == j:
                        matrixM[i][j] = 1
                        matrixMInverse[i][j] = 1
                    else:
                        matrixM[i][j] = 0
                        matrixMInverse[i][j] = 0
        
        tempArray1 = matrixM.copy()
        tempArray2 = matrixMInverse.copy()
        
        print()
        print(f"MatrixM{m-k}inverse")
        print(np.array(matrixMInverse))
        print(f"MatrixA{k+1}")
        print(np.array(P))
        print(f"MatrixM{m-k}")
        print(np.array(matrixM))
        
        P = multiply3Arrays(tempArray2, P, tempArray1)
    return P

In [3]:
## Coefficients 
t = 7.0
k = 3 * (3 - 4) + 1
a = 0.11 * t
b = 0.02 * k
g = 0.02 * k
d = 0.015 * t

matrixA = np.array([
    [6.26 + a, 1.10 - b, 0.97 + g, 1.24 - d],
    [1.10 - b, 4.16 - a, 1.30, 0.16],
    [0.97 + g, 1.30, 5.44 + a, 2.1],
    [1.24 - d, 0.16, 2.10, 6.10 - a]
])

print("Matrix A: ")
matrixA

Matrix A: 


array([[7.03 , 1.14 , 0.93 , 1.135],
       [1.14 , 3.39 , 1.3  , 0.16 ],
       [0.93 , 1.3  , 6.21 , 2.1  ],
       [1.135, 0.16 , 2.1  , 5.33 ]])

In [4]:
normal_form = matrixA_to_normal_frobenius_form(matrixA)
print("Array A in normal form P: ")
normal_form



MatrixM3inverse
[[1.    0.    0.    0.   ]
 [0.    1.    0.    0.   ]
 [1.135 0.16  2.1   5.33 ]
 [0.    0.    0.    1.   ]]
MatrixA1
[[7.03  1.14  0.93  1.135]
 [1.14  3.39  1.3   0.16 ]
 [0.93  1.3   6.21  2.1  ]
 [1.135 0.16  2.1   5.33 ]]
MatrixM3
[[ 1.       0.       0.       0.     ]
 [ 0.       1.       0.       0.     ]
 [-0.54048 -0.07619  0.47619 -2.5381 ]
 [ 0.       0.       0.       1.     ]]

MatrixM2inverse
[[  1.        0.        0.        0.     ]
 [  2.38318   3.47643  12.14169 -30.58249]
 [  0.        0.        1.        0.     ]
 [  0.        0.        0.        1.     ]]
MatrixA2
[[  6.52736   1.06914   0.44286  -1.22543]
 [  0.43738   3.29095   0.61905  -3.13952]
 [  2.38318   3.47643  12.14169 -30.58249]
 [  0.        0.        1.        0.     ]]
MatrixM2
[[ 1.       0.       0.       0.     ]
 [-0.68553  0.28765 -3.49257  8.7971 ]
 [ 0.       0.       1.       0.     ]
 [ 0.       0.       0.       1.     ]]

MatrixM1inverse
[[  7.48677  16.16557 -76.23167 109

[[21.96, -167.59947499999998, 526.3041860000001, -571.6580448124994],
 [1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0]]