# Варіант 10

In [5]:
import warnings 
warnings.filterwarnings("ignore")

In [1]:
import numpy as np

def square_root_method(A, b, precision=6):
    n = len(A)
    T = np.zeros((n, n))
    
    print("Початкова матриця A:")
    print(np.round(A, precision))
    print("\nПочатковий вектор b:")
    print(np.round(b, precision))
    
    for i in range(n):
        for j in range(i, n):
            if i == j:
                sum_k = sum(T[k, i]**2 for k in range(i))
                T[i, i] = np.sqrt(A[i, i] - sum_k)
            else:
                sum_k = sum(T[k, i] * T[k, j] for k in range(i))
                T[i, j] = (A[i, j] - sum_k) / T[i, i]
            
            T[i, j] = round(T[i, j], precision)
            
        print(f"Матриця під час факторизації ({i}й рядок)\n {T}")
    
    print("\nМатриця T після факторизації:")
    print(np.round(T, precision))
    

    y = np.zeros(n)
    for i in range(n):
        sum_k = sum(T[k, i] * y[k] for k in range(i))
        y[i] = (b[i] - sum_k) / T[i, i]
        y[i] = round(y[i], precision)
    
    print("\nПроміжний вектор y:")
    print(np.round(y, precision))
    
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        sum_k = sum(T[i, k] * x[k] for k in range(i+1, n))
        x[i] = (y[i] - sum_k) / T[i, i]
        x[i] = round(x[i], precision)
    
    return x

# Використання методу
A = np.array([
    [1.0, 0.42, 0.54, 0.66],
    [0.42, 1.0, 0.32, 0.44],
    [0.54, 0.32, 1.0, 0.22],
    [0.66, 0.44, 0.22, 1.0]
])

b = np.array([0.3, 0.5, 0.7, 0.9])

x = square_root_method(A, b)

print("\nРозв'язок x:")
print(np.round(x, 6))

# Перевірка
r = b - np.dot(A, x)
print("\nВектор нев'язки r = b - Ax:")
print(np.round(r, 6))

Початкова матриця A:
[[1.   0.42 0.54 0.66]
 [0.42 1.   0.32 0.44]
 [0.54 0.32 1.   0.22]
 [0.66 0.44 0.22 1.  ]]

Початковий вектор b:
[0.3 0.5 0.7 0.9]
Матриця під час факторизації (0й рядок)
 [[1.   0.42 0.54 0.66]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]]
Матриця під час факторизації (1й рядок)
 [[1.       0.42     0.54     0.66    ]
 [0.       0.907524 0.102697 0.179389]
 [0.       0.       0.       0.      ]
 [0.       0.       0.       0.      ]]
Матриця під час факторизації (2й рядок)
 [[ 1.        0.42      0.54      0.66    ]
 [ 0.        0.907524  0.102697  0.179389]
 [ 0.        0.        0.835376 -0.185333]
 [ 0.        0.        0.        0.      ]]
Матриця під час факторизації (3й рядок)
 [[ 1.        0.42      0.54      0.66    ]
 [ 0.        0.907524  0.102697  0.179389]
 [ 0.        0.        0.835376 -0.185333]
 [ 0.        0.        0.        0.7056  ]]

Матриця T після факторизації:
[[ 1.        0.42      0.54      0.66    ]
 [ 0.       

\documentclass[10pt]{article}
\usepackage[ukrainian]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage[version=4]{mhchem}
\usepackage{stmaryrd}
\usepackage{graphicx}
\usepackage[export]{adjustbox}
\graphicspath{ {./images/} }

\begin{document}
\section*{1 Теоретичні відомості}
Будемо розглядати системи вигляду


\begin{equation*}
A x=b \tag{1}
\end{equation*}


де $A(n \times n)$ - матриця системи, $b$ - вектор правої частини, $x$ - вектор розв'язку.

\section*{Метод Гауса}
Метод складається з двох етапів:

\begin{enumerate}
  \item прямого хода методу (приведення системи (1) до еквівалентної системи з трикутною матрицею);

  \item зворотного ходу (визначення невідомого вектору $x$ ) .

\end{enumerate}

Існує декілька варіантів методу Гауса.

Схема з вибором головного елемента полягає у наступному:

\begin{enumerate}
  \item Прямий хід.
\end{enumerate}

1.1) Відшукати $a_{\text {main }}=\max _{i, j}\left|a_{i, j}\right|, i, j=1 . . n$. Нехай $a_{\text {main }}=a_{p q}$. Рядок $p$ називається головним.

1.2) Обчислити множники $m_{i}=\frac{a_{i q}}{a_{p q}}, i \neq p$.

1.3) 3 кожного $i$-го неголовного рядка віднімаємо покомпонентно головний рядок, який помножено на $m_{i}:$

$$
a_{i j}:=a_{i j}-m_{i} a_{p j}, \quad i \neq p, j=1 . . n
$$

для вектора правої частини:

$$
b_{i}:=b_{i}-m_{i} b_{p}
$$

В результаті отримуємо матрицю, де всі елементи стовпця $q$, крім $a_{p q \text {, дорівнюють }}$, нулю. Відкидаючи стовпець $q$ та головний рядок $p$, і відповідний елемент $b_{p}$, отримуємо систему 3 матрицею $A_{1}((n-1) \times(n-1))$. Якщо $n-1>1$, покладаємо $n:=n-1$, і переходимо до п.1.1, інакше переходимо до п.2.

\includegraphics[max width=\textwidth, center]{2024_06_25_8685d8a29b72df6c5923g-2}\\
у окремому масиві, оскільки вони знадобляться в п.2).

\begin{enumerate}
  \setcounter{enumi}{1}
  \item Зворотний хід.
\end{enumerate}

2.1) Складаємо систему, еквівалентну вихідній, що складається з головних рядків, які отримувались у п.1. Права частина складається з відповідних елементів $b_{p}$. Отримана система має трикутну матрицю. Знаходимо послідовно значення елементів $x_{i}$.

\section*{Метод квадратного кореня}
Метод використовується для розв’язання СЛАР виду (1), у яких матриця $A$ є симетричною, тобто

$$
a_{i j}=a_{j i} \forall i, j
$$

Метод полягає у наступному:

\begin{enumerate}
  \item Прямий хід: факторизація $A=T ' T$, де
\end{enumerate}

$$
T=\left(\begin{array}{cccc}
t_{11} & t_{12} & \ldots & t_{1 n} \\
0 & t_{22} & \ldots & t_{2 n} \\
\ldots & \ldots & \ldots & \ldots \\
0 & 0 & \ldots & t_{n n}
\end{array}\right), T^{\prime}=\left(\begin{array}{cccc}
t_{11} & 0 & . . & 0 \\
t_{12} & t_{22} & \ldots & 0 \\
\ldots & \ldots & \ldots & \ldots \\
t_{1 n} & t_{2 n} & \ldots & t_{n n}
\end{array}\right)
$$

1.1) Знаходимо елементи $t_{i j}$ матриць-множників:

$$
\begin{gathered}
t_{11}=\sqrt{a_{11}}, t_{1 j}=\frac{a_{1 j}}{t_{11}}(j>1), \\
t_{i i}=\sqrt{a_{i i}-\sum_{k=1}^{i-1} t_{k i}^{2}}(1<i \leq n), \\
t_{i j}=\frac{a_{i j}-\sum_{k=1}^{i-1} t_{k i} t_{k j}}{t_{i i}}(i<j), \\
t_{i j}=0(i>j)
\end{gathered}
$$

1.2) Формуємо замість вихідної системи дві наступні системи:

$$
T^{\prime} y=b, T x=y
$$

\begin{enumerate}
  \setcounter{enumi}{1}
  \item Зворотний хід.
\end{enumerate}

2.1) Послідовно знаходимо:

$$
\begin{gathered}
y_{1}=\frac{b_{1}}{t_{11}}, y_{i}=\frac{b_{i}-\sum_{k=1}^{i-1} t_{k i} y_{k}}{t_{i i}}(i>1) \\
x_{n}=\frac{y_{n}}{t_{n n}}, x_{i}=\frac{y_{i}-\sum_{k=i+1}^{n} t_{i k} x_{k}}{t_{i i}}(i<n)
\end{gathered}
$$

\section*{2 Завдання}
Розв'язати систему рівнянь 3 кількістю значущих цифр $m=6$.

Якщо матриця системи симетрична, то розв'язання проводити за методом квадратних коренів, якщо матриця системи несиметрична, то використати метод Гауса.

Вивести всі проміжні результати (матриці $A$, що отримані в ході прямого ходу методу Гауса, матрицю зворотного ходу методу Гауса, або матрицю $T$ та вектор $у$ для методу квадратних коренів) та розв'язок системи.

Навести результат перевірки: вектор нев'язки $\boldsymbol{r}=\boldsymbol{b}-\boldsymbol{A} \boldsymbol{x}$, де $\boldsymbol{x}$ - отриманий розв'язок.

Розв’язати задану систему рівнянь за допомогою програмного забезпечення Mathcad. Навести результат перевірки: вектор нев'язки $\boldsymbol{r}=\boldsymbol{b}-\boldsymbol{A} \boldsymbol{x}_{\boldsymbol{m}}$, де $\boldsymbol{x}_{\boldsymbol{m}}$ - отриманий у Mathcad розв'язок.

Порівняти корені рівнянь, отримані у Mathcad, із власними результатами за допомогою методу середньоквадратичної похибки:

$$
\delta=\sqrt{\frac{1}{n} \sum_{k=1}^{n}\left(x_{k}-x_{m k}\right)^{2}} \text {, }
$$

де $\boldsymbol{x}$ - отриманий у програмі розв'язок, $\boldsymbol{x}_{\boldsymbol{m}}$ - отриманий у Mathcad розв'язок.

Зазвичай при використанні для обчислень 4-байтових чисел (тип float y Visual C++) порядок $\delta$ :

\begin{itemize}
  \item у методі Гауса - $10^{-4}-10^{-6}$,
  \item у методі квадратних коренів $-10^{-5}-10^{-7}$, бувають і повні співпадіння рішень до 6 знаків після коми.
\end{itemize}

\end{document}
