In [67]:
import numpy as np
np.set_printoptions(precision=5, suppress=False)

In [68]:
t = 7.0
k = 3 * (3 - 4) + 1
a = 0.11 * t
b = 0.02 * k
g = 0.02 * k
d = 0.015 * t

matrixA = np.array([
    [6.26 + a, 1.10 - b, 0.97 + g, 1.24 - d],
    [1.10 - b, 4.16 - a, 1.30, 0.16],
    [0.97 + g, 1.30, 5.44 + a, 2.1],
    [1.24 - d, 0.16, 2.10, 6.10 - a]
])

print("Matrix A: ")
matrixA

Matrix A: 


array([[7.03 , 1.14 , 0.93 , 1.135],
       [1.14 , 3.39 , 1.3  , 0.16 ],
       [0.93 , 1.3  , 6.21 , 2.1  ],
       [1.135, 0.16 , 2.1  , 5.33 ]])

In [69]:
import numpy as np
from scipy import linalg

# Вхідна матриця
A = np.array([
    [7.03, 1.14, 0.93, 1.135],
    [1.14, 3.39, 1.3, 0.16],
    [0.93, 1.3, 6.21, 2.1],
    [1.135, 0.16, 2.1, 5.33]
])



# Перший етап
M3 = np.eye(4)
M3[2, :] = [-A[3,0]/A[3,2], -A[3,1]/A[3,2], 1/A[3,2], -A[3,3]/A[3,2]]

print("M3")
print(M3)


A1 = np.linalg.inv(M3) @ A @ M3

print("A1")
print(A1)


# Другий етап
M2 = np.eye(4)
M2[1, :] = [-A1[2,0]/A1[2,1], 1/A1[2,1], -A1[2,2]/A1[2,1], -A1[2,3]/A1[2,1]]
print("M2")
print(M2)


A2 = np.linalg.inv(M2) @ A1 @ M2

print("A2")
print(A2)


# Третій етап
M1 = np.eye(4)
M1[0, :] = [1/A2[1,0], -A2[1,1]/A2[1,0], -A2[1,2]/A2[1,0], -A2[1,3]/A2[1,0]]
print("M1")
print(M1)


P = np.linalg.inv(M1) @ A2 @ M1import numpy as np
from scipy import linalg

# Вхідна матриця
A = np.array([
    [7.03, 1.14, 0.93, 1.135],
    [1.14, 3.39, 1.3, 0.16],
    [0.93, 1.3, 6.21, 2.1],
    [1.135, 0.16, 2.1, 5.33]
])



# Перший етап
M3 = np.eye(4)
M3[2, :] = [-A[3,0]/A[3,2], -A[3,1]/A[3,2], 1/A[3,2], -A[3,3]/A[3,2]]

print("M3")
print(M3)


A1 = np.linalg.inv(M3) @ A @ M3

print("A1")
print(A1)


# Другий етап
M2 = np.eye(4)
M2[1, :] = [-A1[2,0]/A1[2,1], 1/A1[2,1], -A1[2,2]/A1[2,1], -A1[2,3]/A1[2,1]]
print("M2")
print(M2)


A2 = np.linalg.inv(M2) @ A1 @ M2

print("A2")
print(A2)


# Третій етап
M1 = np.eye(4)
M1[0, :] = [1/A2[1,0], -A2[1,1]/A2[1,0], -A2[1,2]/A2[1,0], -A2[1,3]/A2[1,0]]
print("M1")
print(M1)


P = np.linalg.inv(M1) @ A2 @ M1

V = np.array([-P[0,3], -P[0,2], -P[0,1], -P[0,0], 1])
lambda_values = np.roots(V[::-1])

print("Власні значення:")
for i, l in enumerate(lambda_values, 1):
    print(f"λ_{i} = {l:.5f}")

Y = np.array([
    [l**3, l**2, l, 1] for l in lambda_values
])


S = M3 @ M2 @ M1
print("Матрция подібності")
print(S)
eigenvectors = S @ Y.T

print("\nВласні вектори:")
for i, v in enumerate(eigenvectors.T, 1):
    print(f"v_{i} = {v}")

print("\nПеревірка точності:")
for i, (lambda_i, v) in enumerate(zip(lambda_values, eigenvectors.T), 1):
    error = np.linalg.norm(A @ v - lambda_i * v)
    print(f"Помилка для λ_{i}: {error:.2e}")

print("\nВласні значення за допомогою numpy:")
np_eigenvalues, np_eigenvectors = np.linalg.eig(A)
for i, ev in enumerate(np_eigenvalues, 1):
    print(f"λ_{i} = {ev:.5f}")

V = np.array([-P[0,3], -P[0,2], -P[0,1], -P[0,0], 1])
lambda_values = np.roots(V[::-1])

print("Власні значення:")
for i, l in enumerate(lambda_values, 1):
    print(f"λ_{i} = {l:.5f}")

Y = np.array([
    [l**3, l**2, l, 1] for l in lambda_values
])


S = M3 @ M2 @ M1
print("Матрция подібності")
print(S)
eigenvectors = S @ Y.T

print("\nВласні вектори:")
for i, v in enumerate(eigenvectors.T, 1):
    print(f"v_{i} = {v}")

print("\nПеревірка точності:")
for i, (lambda_i, v) in enumerate(zip(lambda_values, eigenvectors.T), 1):
    error = np.linalg.norm(A @ v - lambda_i * v)
    print(f"Помилка для λ_{i}: {error:.2e}")

print("\nВласні значення за допомогою numpy:")
np_eigenvalues, np_eigenvectors = np.linalg.eig(A)
for i, ev in enumerate(np_eigenvalues, 1):
    print(f"λ_{i} = {ev:.5f}")

M3
[[ 1.       0.       0.       0.     ]
 [ 0.       1.       0.       0.     ]
 [-0.54048 -0.07619  0.47619 -2.5381 ]
 [ 0.       0.       0.       1.     ]]
A1
[[ 6.52736e+00  1.06914e+00  4.42857e-01 -1.22543e+00]
 [ 4.37381e-01  3.29095e+00  6.19048e-01 -3.13952e+00]
 [ 2.38318e+00  3.47643e+00  1.21417e+01 -3.05825e+01]
 [ 2.97117e-17  1.12741e-17  1.00000e+00  0.00000e+00]]
M2
[[ 1.       0.       0.       0.     ]
 [-0.68553  0.28765 -3.49257  8.7971 ]
 [ 0.       0.       1.       0.     ]
 [ 0.       0.       0.       1.     ]]
A2
[[ 5.79443e+00  3.07540e-01 -3.29120e+00  8.17992e+00]
 [ 7.48677e+00  1.61656e+01 -7.62317e+01  1.09225e+02]
 [-4.02313e-17  1.00000e+00  0.00000e+00  0.00000e+00]
 [ 2.19830e-17  3.24300e-18  1.00000e+00  9.91789e-17]]
M1
[[  0.13357  -2.15922  10.18218 -14.58912]
 [  0.        1.        0.        0.     ]
 [  0.        0.        1.        0.     ]
 [  0.        0.        0.        1.     ]]
Власні значення:
λ_1 = 9.38916
λ_2 = 6.00237
λ_3 = 4.085